tensorchord/pgvecto.rs-docs

src/getting-started/overview.md
Ref https://github.com/tensorchord/pgvecto.rs/pull/231
=> fix: Fix the cosine distance def

.vitepress/config.mts, src/admin/upgrading.md, src/getting-started/overview.md, src/usage/indexing.md, src/usage/monitoring.md, src/usage/search.md
* PR in pgvecto.rs: https://github.com/tensorchord/pgvecto.rs/pull/248
* PR in pgvecto.rs-docs: https://github.com/tensorchord/pgvecto.rs-docs/pull/7
=> docs for "refactor: orthogonal support of vbase and prefilter"

.vitepress/config.mts, src/admin/upgrading.md, src/reference/schema.md, src/usage/monitoring.md
* PR in pgvecto.rs: https://github.com/tensorchord/pgvecto.rs/pull/254
* PR in pgvecto.rs-docs: https://github.com/tensorchord/pgvecto.rs-docs/pull/8
=> docs for "chore: stable schema generation"

.gitignore, .vitepress/config.mts, src/getting-started/installation.md, src/getting-started/overview.md, src/integration/langchain.md
Ref https://github.com/tensorchord/pgvecto.rs/issues/245
cc @BeautyyuYanli
=> feat: Add langchain integration

src/developers/development.md
* https://github.com/tensorchord/pgvecto.rs/pull/265
* https://github.com/tensorchord/pgvecto.rs-docs/pull/11
=> docs for "docs: advice developers to setup all PostgreSQL versions"

.vitepress/config.mts, README.md, src/admin/kubernetes.md
fix https://github.com/tensorchord/pgvecto.rs/issues/211#issuecomment-1882224988
=> feat: Add how to use pgvecto.rs in Kubernetes

.vitepress/config.mts, src/use-cases/hybrid-search.md
Close https://github.com/tensorchord/pgvecto.rs/issues/257
Preview: https://pgvecto-rs-docs-git-fork-gaocegege-hybrid-tensorchord.vercel.app/use-cases/hybrid-search.html
=> feat: Add hybrid search doc

src/getting-started/installation.md
* pgvecto.rs: https://github.com/tensorchord/pgvecto.rs/pull/273
* pgvecto.rs-docs: https://github.com/tensorchord/pgvecto.rs-docs/pull/19
=> docs for 'chore: set schema and search_path'

.vitepress/config.mts, src/admin/fdw.md, src/usage/quantization.md
- fix https://github.com/tensorchord/pgvecto.rs/issues/258
=> add quantization doc

src/community/roadmap.md
Signed-off-by: Jinjing.Zhou <allenzhou@tensorchord.ai>
=> docs: Roadmap

src/community/roadmap.md
Signed-off-by: Jinjing.Zhou <allenzhou@tensorchord.ai>
=> doc: fix typo

src/community/roadmap.md, src/index.md
Signed-off-by: Jinjing.Zhou <allenzhou@tensorchord.ai>
=> docs: fix description in index page

src/integration/langchain.md, src/integration/llama-index.md
Close https://github.com/tensorchord/pgvecto.rs/issues/245
=> feat: Add llama index

.vitepress/config.mts, src/reference/indexing_options.md, src/reference/schema.md, src/usage/indexing.md
@gaocegege @VoVAllen Any suggestions?
=> Rewrite indexing

src/admin/upgrading.md
* pgvecto.rs: https://github.com/tensorchord/pgvecto.rs/pull/313
* pgvecto.rs-docs: https://github.com/tensorchord/pgvecto.rs-docs/pull/38
=> docs for "refactor: refine upgrade process"

.vitepress/config.mts, src/reference/search_options.md, src/usage/compatibility.md, src/usage/search.md
=> doc: search rewrite

src/developers/development.md
=> fix: install cargo-pgrx shell script in development.md

src/getting-started/overview.md, src/reference/schema.md, src/usage/indexing.md
- feature PR: https://github.com/tensorchord/pgvecto.rs/pull/299
=> doc: sparse vector

src/reference/schema.md
https://github.com/tensorchord/pgvecto.rs/issues/255
=> docs: document pgvectors_upgrade and text2vec_openai in schema

.vitepress/config.mts
Signed-off-by: Jinjing.Zhou <allenzhou@tensorchord.ai>
=> add sitemap

src/admin/upgrading.md
https://github.com/tensorchord/pgvecto.rs/issues/616#issuecomment-2568773680
=> addtional operation for 0.4.0

.vitepress/config.mts, src/vectorchord/getting-started/overview.md, src/vectorchord/usage/indexing-with-maxsim-operators.md, src/vectorchord/usage/indexing.md, src/vectorchord/usage/performance-tuning.md
DO NOT MERGE IT BEFORE 0.3.0 releases
=> add maxsim document

src/vectorchord/admin/migration.md
fix https://github.com/tensorchord/VectorChord/issues/257
=> fix dockerhub link
